### ISSUE TITLE
feat: allow users to share code examples

### ISSUE THREAD

**Issue by peterjokumsen** [lgpage/rxtutor#230]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Be able to get a permalink to the code example I've created.
I would like to be able to share my code, for others to see the example of what the code does.

**Describe alternatives you've considered**
2 possible approaches considered:
- Possibly get user to auth with GitHub and when they want to share a permalink create a repo for them to store the session and build up a URL to reference the change, i.e. `/examples/{username}/{id}`
- Make a deterministic hash of the code user created, be able to re-generate the code from that hash

**Additional context**
Like sharing regular expression examples in [regexr](https://regexr.com/).

**Comment by peterjokumsen** [comment]
@lgpage for your consideration ;)

**Comment by lgpage** [comment]
I like it.
Ideally #262 should be completed first to avoid rework

**Comment by peterjokumsen** [comment]
Lekker, will start playing around with it this weekend 🫡🥳

**Comment by lgpage** [comment]
@peterjokumsen sweet.
I am busy working on #262 atm (should have it done by the weekend)

**Comment by peterjokumsen** [comment]
Perfect stuff @lgpage 🤘🏻 good luck 😉
